# Generated by Django 2.2.5 on 2019-09-08 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=64)),
                ('share_count', models.IntegerField()),
                ('price', models.FloatField()),
                ('gross_value', models.FloatField()),
                ('trade_cost', models.FloatField()),
                ('net_value', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_txs', to='stock.StockMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
