# Generated by Django 2.2.5 on 2019-09-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stocktx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmaster',
            old_name='total_value',
            new_name='market_value',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='industry',
        ),
    ]
