# Generated by Django 2.2.5 on 2019-09-20 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_create_stock_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktx',
            name='tx_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
