# Generated by Django 2.2.5 on 2019-09-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stocktx_tx_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktx',
            old_name='tx_date',
            new_name='tx_at',
        ),
    ]
