# Generated by Django 2.2.5 on 2019-10-01 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0008_ccassparticipantmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCASSParticipantDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stock_code', models.CharField(max_length=64)),
                ('detail_date', models.DateField()),
                ('share_count', models.BigIntegerField()),
                ('share_percent', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participant_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.CCASSParticipantMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
