# Generated by Django 2.2.5 on 2019-10-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20191002_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktx',
            name='tx_at',
            field=models.DateField(),
        ),
    ]
