# Generated by Django 2.2.5 on 2019-10-05 13:50

from django.db import migrations

from stock.stk_sector.utils import create_stock_sectors


def run_script(*args, **kwargs):
    create_stock_sectors()


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_stocksectormaster'),
    ]

    operations = [
        migrations.RunPython(
            run_script,
            migrations.RunPython.noop
        )
    ]
