# Generated by Django 2.2.5 on 2019-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_stockmaster_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaster',
            name='unrealized_value',
            field=models.FloatField(default=0.0),
        ),
    ]
