# Generated by Django 2.2.5 on 2019-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_stockmaster_unrealized_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaster',
            name='turnover',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockmaster',
            name='unrealized_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
