# Generated by Django 2.2.5 on 2019-10-07 15:45

from django.db import migrations

from base.utils import get_admin_user
from general.gnl_syslog.utils import write_syslog
from stock.stk_tx.utils import get_stock_master_unrealized_cost


def run_script(*args, **kwargs):
    from stock.models import StockMaster

    stock_masters = StockMaster.objects.all()
    total_len, CHUNK_SIZE = stock_masters.count(), 1000
    fields = ['unrealized_cost', ]
    w_debug(f'total {total_len}')

    for idx in range(0, total_len, CHUNK_SIZE):
        end_idx = idx + CHUNK_SIZE
        stock_master_chunks = stock_masters[idx:end_idx]
        u_sms = get_updated_stock_masters(stock_master_chunks, total_len)
        StockMaster.objects.bulk_update(u_sms, fields)
        w_debug(f'{end_idx}/{total_len}')

    w_debug(f'finished')


def get_updated_stock_masters(stock_masters, total_len):
    updated_stock_masters = []
    for idx, stock_master in enumerate(stock_masters):
        unrealized_cost = get_stock_master_unrealized_cost(stock_master)
        stock_master.unrealized_cost = unrealized_cost
        updated_stock_masters.append(stock_master)
    return updated_stock_masters


def w_debug(message):
    admin_user = get_admin_user()
    name = 'update_stock_unrealized_cost'
    write_syslog(name, message, admin_user, is_print=True)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20191006_2010'),
    ]

    operations = [
        migrations.RunPython(
            run_script,
            migrations.RunPython.noop
        )
    ]
