# Generated by Django 2.2.5 on 2019-10-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0017_update_stock_unrealized_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlertMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('stock_code', models.CharField(max_length=16)),
                ('market_price_value', models.FloatField(default=0)),
                ('market_price_condition', models.CharField(choices=[('COND_ABOVE', 'When value is above'), ('COND_BELOW', 'When value is below')], default='COND_ABOVE', max_length=16)),
                ('ccass_percent_value', models.FloatField(default=0)),
                ('ccass_percent_condition', models.CharField(choices=[('COND_ABOVE', 'When value is above'), ('COND_BELOW', 'When value is below')], default='COND_ABOVE', max_length=16)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
