# Generated by Django 2.2.5 on 2019-10-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_stockalertmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalertmaster',
            name='ccass_percent_trigger_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockalertmaster',
            name='market_price_trigger_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
