# Generated by Django 2.2.5 on 2019-10-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20191010_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccassparticipantmaster',
            name='participant_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
