# Generated by Django 2.2.5 on 2019-10-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20191012_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktx',
            name='tx_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend')], max_length=64),
        ),
    ]
