# Generated by Django 2.2.5 on 2019-10-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_auto_20191023_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockccassandpricesummarydetail',
            name='turnover',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
