# Generated by Django 2.2.5 on 2019-11-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_stockccassandpricesummarydetail_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockccassandpricesummarydetail',
            name='participant_share',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
