service: casualapp-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  memorySize: 128
functions:
  app:
    handler: dist/server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
  # triggerGenComicMasters:
  #   handler: dist/handlers/triggerGenComicMasters.handler
  #   events:
  #   - schedule:
  #       rate: cron(*/5 * * * ? *)
  #       enabled: true
