# Generated by Django 2.2.5 on 2019-09-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_mediamaster'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmaster',
            name='images',
            field=models.ManyToManyField(to='general.MediaMaster'),
        ),
    ]
