# Generated by Django 2.2.5 on 2019-09-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20190909_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalmaster',
            old_name='images',
            new_name='medias',
        ),
    ]
