# Generated by Django 2.2.5 on 2019-09-22 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_chessboardresultmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessBoardCalculateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('board', models.CharField(max_length=90)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('move_request_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_calculate_masters', to='game.ChessMoveRequestMaster')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='game.ChessBoardCalculateMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
