# Generated by Django 2.2.5 on 2019-09-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_chessboardcalculatemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboardcalculatemaster',
            name='level',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
