# Generated by Django 2.2.5 on 2019-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_chessboardcalculatemaster_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboardcalculatemaster',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
