# Generated by Django 2.2.5 on 2019-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_chessboardcalculatemaster_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboardcalculatemaster',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chessboardcalculatemaster',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
