# Generated by Django 2.2.5 on 2019-09-22 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190922_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessboardresultmaster',
            name='to_board',
        ),
        migrations.AddField(
            model_name='chessboardresultmaster',
            name='to_boards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), default=[], size=None),
            preserve_default=False,
        ),
    ]
