# Generated by Django 2.2.5 on 2019-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190922_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboardcalculatemaster',
            name='is_upper_side',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
