# Generated by Django 2.2.5 on 2019-09-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_sudokugamerecordmaster_solution_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudokugamerecordmaster',
            name='is_finished',
        ),
    ]
