# Generated by Django 2.2.5 on 2019-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_sudokugamerecordmaster_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokugamerecordmaster',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('difficult', 'Difficult')], default='easy', max_length=16),
            preserve_default=False,
        ),
    ]
