# Generated by Django 2.2.5 on 2019-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_sudokugamerecordmaster_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokugamerecordmaster',
            name='current_board',
            field=models.CharField(default='_________________________________________________________________________________', max_length=81),
        ),
        migrations.AlterField(
            model_name='sudokugamerecordmaster',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('difficult', 'Difficult')], default='easy', max_length=16),
        ),
        migrations.AlterField(
            model_name='sudokugamerecordmaster',
            name='solution_board',
            field=models.CharField(default='_________________________________________________________________________________', max_length=81),
        ),
        migrations.AlterField(
            model_name='sudokugamerecordmaster',
            name='start_board',
            field=models.CharField(default='_________________________________________________________________________________', max_length=81),
        ),
    ]
