# Generated by Django 2.2.5 on 2019-09-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='catagory',
            field=models.CharField(max_length=128),
        ),
    ]
