# Generated by Django 2.2.5 on 2019-09-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_mediamaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamaster',
            name='access_url',
            field=models.CharField(max_length=256),
        ),
    ]
