# Generated by Django 2.2.5 on 2019-09-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20190929_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediamaster',
            old_name='access_url',
            new_name='file_name',
        ),
    ]
