# Generated by Django 2.2.5 on 2019-09-29 01:37

from django.conf import settings
from django.db import migrations

from base.utils import get_admin_user
from general.models import MediaMaster
from general.gnl_syslog.utils import write_syslog
from general.gnl_lookup.utils import get_lookup_value


def w_debug(message):
    admin_user = get_admin_user()
    write_syslog('update_media_master_file_name',
                 message,
                 admin_user,
                 is_print=True
                 )


def get_replace_path():
    IS_DEVELOPMENT = settings.IS_DEVELOPMENT
    host_name = get_lookup_value('HOST_NAME')
    if settings.IS_DEVELOPMENT:
        return f'{host_name}/static/m/'
    return f'{host_name}/media/'


def update_media_master_file_name(*args, **kwargs):

    media_masters = MediaMaster.objects.all()
    media_masters_count = media_masters.count()

    replace_path = get_replace_path()

    w_debug(f'begin: {replace_path} {media_masters_count}')

    for idx, media_master in enumerate(media_masters):
        media_file_name = media_master.file_name.replace(replace_path, '')
        media_master.file_name = media_file_name
        media_master.save()
        w_debug(f'{idx}/{media_masters_count}: {media_file_name}')


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20190929_0936'),
    ]

    operations = [
        migrations.RunPython(
            update_media_master_file_name,
            migrations.RunPython.noop
        )
    ]
